name: 01 - Building Blocks
on: workflow_dispatch 
#push
# This workflow is designed to demonstrate the basic building blocks of a GitHub Actions workflow.
# change it to workflow_dispatch to trigger it manually from the Actions tab in your repository.
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, world!"
  echo-goodbye:
    runs-on: ubantu-latest
    steps:
      - name: Failed steps
        run: |
          echo "I will fail"
          exit 1 
      - name: Say goodbye
        run: echo "GoodBye"
